//! Protobuf types for the Substreams NEAR block model.
//!
//! Generated by `buf generate`; see `buf.gen.yaml`.

pub mod sf {
    pub mod near {
        pub mod r#type {
            pub mod v1 {
                include!("sf.near.type.v1.mod.rs");
            }
        }
    }
}
