// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/near/type/v1/type.proto

pub mod state_change_cause {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Cause {
        NotWritableToDisk(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::NotWritableToDisk,
            >,
        ),
        InitialState(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::InitialState,
            >,
        ),
        TransactionProcessing(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::TransactionProcessing,
            >,
        ),
        ActionReceiptProcessingStarted(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::ActionReceiptProcessingStarted,
            >,
        ),
        ActionReceiptGasReward(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::ActionReceiptGasReward,
            >,
        ),
        ReceiptProcessing(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::ReceiptProcessing,
            >,
        ),
        PostponedReceipt(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::PostponedReceipt,
            >,
        ),
        UpdatedDelayedReceipts(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::UpdatedDelayedReceipts,
            >,
        ),
        ValidatorAccountsUpdate(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::ValidatorAccountsUpdate,
            >,
        ),
        Migration(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_cause::Migration,
            >,
        ),
    }
    impl ::buffa::Oneof for Cause {}
    impl From<super::super::super::state_change_cause::NotWritableToDisk> for Cause {
        fn from(v: super::super::super::state_change_cause::NotWritableToDisk) -> Self {
            Self::NotWritableToDisk(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::NotWritableToDisk>
    for ::core::option::Option<Cause> {
        fn from(v: super::super::super::state_change_cause::NotWritableToDisk) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::InitialState> for Cause {
        fn from(v: super::super::super::state_change_cause::InitialState) -> Self {
            Self::InitialState(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::InitialState>
    for ::core::option::Option<Cause> {
        fn from(v: super::super::super::state_change_cause::InitialState) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::TransactionProcessing> for Cause {
        fn from(
            v: super::super::super::state_change_cause::TransactionProcessing,
        ) -> Self {
            Self::TransactionProcessing(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::TransactionProcessing>
    for ::core::option::Option<Cause> {
        fn from(
            v: super::super::super::state_change_cause::TransactionProcessing,
        ) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::ActionReceiptProcessingStarted>
    for Cause {
        fn from(
            v: super::super::super::state_change_cause::ActionReceiptProcessingStarted,
        ) -> Self {
            Self::ActionReceiptProcessingStarted(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::ActionReceiptProcessingStarted>
    for ::core::option::Option<Cause> {
        fn from(
            v: super::super::super::state_change_cause::ActionReceiptProcessingStarted,
        ) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::ActionReceiptGasReward>
    for Cause {
        fn from(
            v: super::super::super::state_change_cause::ActionReceiptGasReward,
        ) -> Self {
            Self::ActionReceiptGasReward(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::ActionReceiptGasReward>
    for ::core::option::Option<Cause> {
        fn from(
            v: super::super::super::state_change_cause::ActionReceiptGasReward,
        ) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::ReceiptProcessing> for Cause {
        fn from(v: super::super::super::state_change_cause::ReceiptProcessing) -> Self {
            Self::ReceiptProcessing(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::ReceiptProcessing>
    for ::core::option::Option<Cause> {
        fn from(v: super::super::super::state_change_cause::ReceiptProcessing) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::PostponedReceipt> for Cause {
        fn from(v: super::super::super::state_change_cause::PostponedReceipt) -> Self {
            Self::PostponedReceipt(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::PostponedReceipt>
    for ::core::option::Option<Cause> {
        fn from(v: super::super::super::state_change_cause::PostponedReceipt) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::UpdatedDelayedReceipts>
    for Cause {
        fn from(
            v: super::super::super::state_change_cause::UpdatedDelayedReceipts,
        ) -> Self {
            Self::UpdatedDelayedReceipts(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::UpdatedDelayedReceipts>
    for ::core::option::Option<Cause> {
        fn from(
            v: super::super::super::state_change_cause::UpdatedDelayedReceipts,
        ) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::ValidatorAccountsUpdate>
    for Cause {
        fn from(
            v: super::super::super::state_change_cause::ValidatorAccountsUpdate,
        ) -> Self {
            Self::ValidatorAccountsUpdate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::ValidatorAccountsUpdate>
    for ::core::option::Option<Cause> {
        fn from(
            v: super::super::super::state_change_cause::ValidatorAccountsUpdate,
        ) -> Self {
            Self::Some(Cause::from(v))
        }
    }
    impl From<super::super::super::state_change_cause::Migration> for Cause {
        fn from(v: super::super::super::state_change_cause::Migration) -> Self {
            Self::Migration(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_cause::Migration>
    for ::core::option::Option<Cause> {
        fn from(v: super::super::super::state_change_cause::Migration) -> Self {
            Self::Some(Cause::from(v))
        }
    }
}
pub mod state_change_value {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Value {
        AccountUpdate(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::AccountUpdate,
            >,
        ),
        AccountDeletion(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::AccountDeletion,
            >,
        ),
        AccessKeyUpdate(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::AccessKeyUpdate,
            >,
        ),
        AccessKeyDeletion(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::AccessKeyDeletion,
            >,
        ),
        DataUpdate(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::DataUpdate,
            >,
        ),
        DataDeletion(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::DataDeletion,
            >,
        ),
        ContractCodeUpdate(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::ContractCodeUpdate,
            >,
        ),
        ContractDeletion(
            ::buffa::alloc::boxed::Box<
                super::super::super::state_change_value::ContractCodeDeletion,
            >,
        ),
    }
    impl ::buffa::Oneof for Value {}
    impl From<super::super::super::state_change_value::AccountUpdate> for Value {
        fn from(v: super::super::super::state_change_value::AccountUpdate) -> Self {
            Self::AccountUpdate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::AccountUpdate>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::AccountUpdate) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::AccountDeletion> for Value {
        fn from(v: super::super::super::state_change_value::AccountDeletion) -> Self {
            Self::AccountDeletion(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::AccountDeletion>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::AccountDeletion) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::AccessKeyUpdate> for Value {
        fn from(v: super::super::super::state_change_value::AccessKeyUpdate) -> Self {
            Self::AccessKeyUpdate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::AccessKeyUpdate>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::AccessKeyUpdate) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::AccessKeyDeletion> for Value {
        fn from(v: super::super::super::state_change_value::AccessKeyDeletion) -> Self {
            Self::AccessKeyDeletion(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::AccessKeyDeletion>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::AccessKeyDeletion) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::DataUpdate> for Value {
        fn from(v: super::super::super::state_change_value::DataUpdate) -> Self {
            Self::DataUpdate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::DataUpdate>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::DataUpdate) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::DataDeletion> for Value {
        fn from(v: super::super::super::state_change_value::DataDeletion) -> Self {
            Self::DataDeletion(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::DataDeletion>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::DataDeletion) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::ContractCodeUpdate> for Value {
        fn from(v: super::super::super::state_change_value::ContractCodeUpdate) -> Self {
            Self::ContractCodeUpdate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::ContractCodeUpdate>
    for ::core::option::Option<Value> {
        fn from(v: super::super::super::state_change_value::ContractCodeUpdate) -> Self {
            Self::Some(Value::from(v))
        }
    }
    impl From<super::super::super::state_change_value::ContractCodeDeletion> for Value {
        fn from(
            v: super::super::super::state_change_value::ContractCodeDeletion,
        ) -> Self {
            Self::ContractDeletion(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::state_change_value::ContractCodeDeletion>
    for ::core::option::Option<Value> {
        fn from(
            v: super::super::super::state_change_value::ContractCodeDeletion,
        ) -> Self {
            Self::Some(Value::from(v))
        }
    }
}
pub mod receipt {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Receipt {
        Action(::buffa::alloc::boxed::Box<super::super::super::ReceiptAction>),
        Data(::buffa::alloc::boxed::Box<super::super::super::ReceiptData>),
        GlobalContractDistribution(
            ::buffa::alloc::boxed::Box<
                super::super::super::ReceiptGlobalContractDistribution,
            >,
        ),
    }
    impl ::buffa::Oneof for Receipt {}
    impl From<super::super::super::ReceiptAction> for Receipt {
        fn from(v: super::super::super::ReceiptAction) -> Self {
            Self::Action(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ReceiptAction> for ::core::option::Option<Receipt> {
        fn from(v: super::super::super::ReceiptAction) -> Self {
            Self::Some(Receipt::from(v))
        }
    }
    impl From<super::super::super::ReceiptData> for Receipt {
        fn from(v: super::super::super::ReceiptData) -> Self {
            Self::Data(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ReceiptData> for ::core::option::Option<Receipt> {
        fn from(v: super::super::super::ReceiptData) -> Self {
            Self::Some(Receipt::from(v))
        }
    }
    impl From<super::super::super::ReceiptGlobalContractDistribution> for Receipt {
        fn from(v: super::super::super::ReceiptGlobalContractDistribution) -> Self {
            Self::GlobalContractDistribution(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ReceiptGlobalContractDistribution>
    for ::core::option::Option<Receipt> {
        fn from(v: super::super::super::ReceiptGlobalContractDistribution) -> Self {
            Self::Some(Receipt::from(v))
        }
    }
}
pub mod receipt_global_contract_distribution {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Id {
        CodeHash(::buffa::alloc::boxed::Box<super::super::super::CryptoHash>),
        AccountId(::buffa::alloc::string::String),
    }
    impl ::buffa::Oneof for Id {}
    impl From<super::super::super::CryptoHash> for Id {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::CodeHash(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CryptoHash> for ::core::option::Option<Id> {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::Some(Id::from(v))
        }
    }
}
pub mod execution_outcome {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Status {
        Unknown(::buffa::alloc::boxed::Box<super::super::super::UnknownExecutionStatus>),
        Failure(::buffa::alloc::boxed::Box<super::super::super::FailureExecutionStatus>),
        SuccessValue(
            ::buffa::alloc::boxed::Box<super::super::super::SuccessValueExecutionStatus>,
        ),
        SuccessReceiptId(
            ::buffa::alloc::boxed::Box<
                super::super::super::SuccessReceiptIdExecutionStatus,
            >,
        ),
    }
    impl ::buffa::Oneof for Status {}
    impl From<super::super::super::UnknownExecutionStatus> for Status {
        fn from(v: super::super::super::UnknownExecutionStatus) -> Self {
            Self::Unknown(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::UnknownExecutionStatus>
    for ::core::option::Option<Status> {
        fn from(v: super::super::super::UnknownExecutionStatus) -> Self {
            Self::Some(Status::from(v))
        }
    }
    impl From<super::super::super::FailureExecutionStatus> for Status {
        fn from(v: super::super::super::FailureExecutionStatus) -> Self {
            Self::Failure(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::FailureExecutionStatus>
    for ::core::option::Option<Status> {
        fn from(v: super::super::super::FailureExecutionStatus) -> Self {
            Self::Some(Status::from(v))
        }
    }
    impl From<super::super::super::SuccessValueExecutionStatus> for Status {
        fn from(v: super::super::super::SuccessValueExecutionStatus) -> Self {
            Self::SuccessValue(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::SuccessValueExecutionStatus>
    for ::core::option::Option<Status> {
        fn from(v: super::super::super::SuccessValueExecutionStatus) -> Self {
            Self::Some(Status::from(v))
        }
    }
    impl From<super::super::super::SuccessReceiptIdExecutionStatus> for Status {
        fn from(v: super::super::super::SuccessReceiptIdExecutionStatus) -> Self {
            Self::SuccessReceiptId(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::SuccessReceiptIdExecutionStatus>
    for ::core::option::Option<Status> {
        fn from(v: super::super::super::SuccessReceiptIdExecutionStatus) -> Self {
            Self::Some(Status::from(v))
        }
    }
}
pub mod failure_execution_status {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Failure {
        ActionError(::buffa::alloc::boxed::Box<super::super::super::ActionError>),
        InvalidTxError(::buffa::EnumValue<super::super::super::InvalidTxError>),
    }
    impl ::buffa::Oneof for Failure {}
    impl From<super::super::super::ActionError> for Failure {
        fn from(v: super::super::super::ActionError) -> Self {
            Self::ActionError(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ActionError> for ::core::option::Option<Failure> {
        fn from(v: super::super::super::ActionError) -> Self {
            Self::Some(Failure::from(v))
        }
    }
}
pub mod action_error {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Kind {
        AccountAlreadyExist(
            ::buffa::alloc::boxed::Box<
                super::super::super::AccountAlreadyExistsErrorKind,
            >,
        ),
        AccountDoesNotExist(
            ::buffa::alloc::boxed::Box<super::super::super::AccountDoesNotExistErrorKind>,
        ),
        CreateAccountOnlyByRegistrar(
            ::buffa::alloc::boxed::Box<
                super::super::super::CreateAccountOnlyByRegistrarErrorKind,
            >,
        ),
        CreateAccountNotAllowed(
            ::buffa::alloc::boxed::Box<
                super::super::super::CreateAccountNotAllowedErrorKind,
            >,
        ),
        ActorNoPermission(
            ::buffa::alloc::boxed::Box<super::super::super::ActorNoPermissionErrorKind>,
        ),
        DeleteKeyDoesNotExist(
            ::buffa::alloc::boxed::Box<
                super::super::super::DeleteKeyDoesNotExistErrorKind,
            >,
        ),
        AddKeyAlreadyExists(
            ::buffa::alloc::boxed::Box<super::super::super::AddKeyAlreadyExistsErrorKind>,
        ),
        DeleteAccountStaking(
            ::buffa::alloc::boxed::Box<
                super::super::super::DeleteAccountStakingErrorKind,
            >,
        ),
        LackBalanceForState(
            ::buffa::alloc::boxed::Box<super::super::super::LackBalanceForStateErrorKind>,
        ),
        TriesToUnstake(
            ::buffa::alloc::boxed::Box<super::super::super::TriesToUnstakeErrorKind>,
        ),
        TriesToStake(
            ::buffa::alloc::boxed::Box<super::super::super::TriesToStakeErrorKind>,
        ),
        InsufficientStake(
            ::buffa::alloc::boxed::Box<super::super::super::InsufficientStakeErrorKind>,
        ),
        FunctionCall(
            ::buffa::alloc::boxed::Box<super::super::super::FunctionCallErrorKind>,
        ),
        NewReceiptValidation(
            ::buffa::alloc::boxed::Box<
                super::super::super::NewReceiptValidationErrorKind,
            >,
        ),
        OnlyImplicitAccountCreationAllowed(
            ::buffa::alloc::boxed::Box<
                super::super::super::OnlyImplicitAccountCreationAllowedErrorKind,
            >,
        ),
        DeleteAccountWithLargeState(
            ::buffa::alloc::boxed::Box<
                super::super::super::DeleteAccountWithLargeStateErrorKind,
            >,
        ),
        DelegateActionInvalidSignature(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionInvalidSignatureKind,
            >,
        ),
        DelegateActionSenderDoesNotMatchTxReceiver(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionSenderDoesNotMatchTxReceiverKind,
            >,
        ),
        DelegateActionExpired(
            ::buffa::alloc::boxed::Box<super::super::super::DelegateActionExpiredKind>,
        ),
        DelegateActionAccessKeyError(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionAccessKeyErrorKind,
            >,
        ),
        DelegateActionInvalidNonce(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionInvalidNonceKind,
            >,
        ),
        DelegateActionNonceTooLarge(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionNonceTooLargeKind,
            >,
        ),
        NonRefundableTransferToExistingAccount(
            ::buffa::alloc::boxed::Box<
                super::super::super::NonRefundableTransferToExistingAccountKind,
            >,
        ),
        GlobalContractDoesNotExist(
            ::buffa::alloc::boxed::Box<super::super::super::GlobalContractDoesNotExist>,
        ),
        GasKeyDoesNotExist(
            ::buffa::alloc::boxed::Box<super::super::super::GasKeyDoesNotExistKind>,
        ),
        InsufficientGasKeyBalance(
            ::buffa::alloc::boxed::Box<
                super::super::super::InsufficientGasKeyBalanceKind,
            >,
        ),
        GasKeyBalanceTooHigh(
            ::buffa::alloc::boxed::Box<super::super::super::GasKeyBalanceTooHighKind>,
        ),
        DelegateActionInvalidNonceIndex(
            ::buffa::alloc::boxed::Box<
                super::super::super::DelegateActionInvalidNonceIndexKind,
            >,
        ),
        TotalPromiseInputSizeExceeded(
            ::buffa::alloc::boxed::Box<
                super::super::super::TotalPromiseInputSizeExceededKind,
            >,
        ),
        ReceiptStorageProofSizeExceeded(
            ::buffa::alloc::boxed::Box<
                super::super::super::ReceiptStorageProofSizeExceededKind,
            >,
        ),
        MalformedUniversalStateInit(
            ::buffa::alloc::boxed::Box<
                super::super::super::MalformedUniversalStateInitKind,
            >,
        ),
        AccountNotInitialized(
            ::buffa::alloc::boxed::Box<super::super::super::AccountNotInitializedKind>,
        ),
    }
    impl ::buffa::Oneof for Kind {}
    impl From<super::super::super::AccountAlreadyExistsErrorKind> for Kind {
        fn from(v: super::super::super::AccountAlreadyExistsErrorKind) -> Self {
            Self::AccountAlreadyExist(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::AccountAlreadyExistsErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::AccountAlreadyExistsErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::AccountDoesNotExistErrorKind> for Kind {
        fn from(v: super::super::super::AccountDoesNotExistErrorKind) -> Self {
            Self::AccountDoesNotExist(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::AccountDoesNotExistErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::AccountDoesNotExistErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::CreateAccountOnlyByRegistrarErrorKind> for Kind {
        fn from(v: super::super::super::CreateAccountOnlyByRegistrarErrorKind) -> Self {
            Self::CreateAccountOnlyByRegistrar(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CreateAccountOnlyByRegistrarErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::CreateAccountOnlyByRegistrarErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::CreateAccountNotAllowedErrorKind> for Kind {
        fn from(v: super::super::super::CreateAccountNotAllowedErrorKind) -> Self {
            Self::CreateAccountNotAllowed(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CreateAccountNotAllowedErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::CreateAccountNotAllowedErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::ActorNoPermissionErrorKind> for Kind {
        fn from(v: super::super::super::ActorNoPermissionErrorKind) -> Self {
            Self::ActorNoPermission(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ActorNoPermissionErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::ActorNoPermissionErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DeleteKeyDoesNotExistErrorKind> for Kind {
        fn from(v: super::super::super::DeleteKeyDoesNotExistErrorKind) -> Self {
            Self::DeleteKeyDoesNotExist(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeleteKeyDoesNotExistErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DeleteKeyDoesNotExistErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::AddKeyAlreadyExistsErrorKind> for Kind {
        fn from(v: super::super::super::AddKeyAlreadyExistsErrorKind) -> Self {
            Self::AddKeyAlreadyExists(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::AddKeyAlreadyExistsErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::AddKeyAlreadyExistsErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DeleteAccountStakingErrorKind> for Kind {
        fn from(v: super::super::super::DeleteAccountStakingErrorKind) -> Self {
            Self::DeleteAccountStaking(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeleteAccountStakingErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DeleteAccountStakingErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::LackBalanceForStateErrorKind> for Kind {
        fn from(v: super::super::super::LackBalanceForStateErrorKind) -> Self {
            Self::LackBalanceForState(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::LackBalanceForStateErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::LackBalanceForStateErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::TriesToUnstakeErrorKind> for Kind {
        fn from(v: super::super::super::TriesToUnstakeErrorKind) -> Self {
            Self::TriesToUnstake(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TriesToUnstakeErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::TriesToUnstakeErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::TriesToStakeErrorKind> for Kind {
        fn from(v: super::super::super::TriesToStakeErrorKind) -> Self {
            Self::TriesToStake(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TriesToStakeErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::TriesToStakeErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::InsufficientStakeErrorKind> for Kind {
        fn from(v: super::super::super::InsufficientStakeErrorKind) -> Self {
            Self::InsufficientStake(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::InsufficientStakeErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::InsufficientStakeErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::FunctionCallErrorKind> for Kind {
        fn from(v: super::super::super::FunctionCallErrorKind) -> Self {
            Self::FunctionCall(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::FunctionCallErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::FunctionCallErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::NewReceiptValidationErrorKind> for Kind {
        fn from(v: super::super::super::NewReceiptValidationErrorKind) -> Self {
            Self::NewReceiptValidation(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::NewReceiptValidationErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::NewReceiptValidationErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::OnlyImplicitAccountCreationAllowedErrorKind>
    for Kind {
        fn from(
            v: super::super::super::OnlyImplicitAccountCreationAllowedErrorKind,
        ) -> Self {
            Self::OnlyImplicitAccountCreationAllowed(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::OnlyImplicitAccountCreationAllowedErrorKind>
    for ::core::option::Option<Kind> {
        fn from(
            v: super::super::super::OnlyImplicitAccountCreationAllowedErrorKind,
        ) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DeleteAccountWithLargeStateErrorKind> for Kind {
        fn from(v: super::super::super::DeleteAccountWithLargeStateErrorKind) -> Self {
            Self::DeleteAccountWithLargeState(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeleteAccountWithLargeStateErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DeleteAccountWithLargeStateErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidSignatureKind> for Kind {
        fn from(v: super::super::super::DelegateActionInvalidSignatureKind) -> Self {
            Self::DelegateActionInvalidSignature(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidSignatureKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionInvalidSignatureKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionSenderDoesNotMatchTxReceiverKind>
    for Kind {
        fn from(
            v: super::super::super::DelegateActionSenderDoesNotMatchTxReceiverKind,
        ) -> Self {
            Self::DelegateActionSenderDoesNotMatchTxReceiver(
                ::buffa::alloc::boxed::Box::new(v),
            )
        }
    }
    impl From<super::super::super::DelegateActionSenderDoesNotMatchTxReceiverKind>
    for ::core::option::Option<Kind> {
        fn from(
            v: super::super::super::DelegateActionSenderDoesNotMatchTxReceiverKind,
        ) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionExpiredKind> for Kind {
        fn from(v: super::super::super::DelegateActionExpiredKind) -> Self {
            Self::DelegateActionExpired(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionExpiredKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionExpiredKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionAccessKeyErrorKind> for Kind {
        fn from(v: super::super::super::DelegateActionAccessKeyErrorKind) -> Self {
            Self::DelegateActionAccessKeyError(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionAccessKeyErrorKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionAccessKeyErrorKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidNonceKind> for Kind {
        fn from(v: super::super::super::DelegateActionInvalidNonceKind) -> Self {
            Self::DelegateActionInvalidNonce(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidNonceKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionInvalidNonceKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionNonceTooLargeKind> for Kind {
        fn from(v: super::super::super::DelegateActionNonceTooLargeKind) -> Self {
            Self::DelegateActionNonceTooLarge(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionNonceTooLargeKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionNonceTooLargeKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::NonRefundableTransferToExistingAccountKind> for Kind {
        fn from(
            v: super::super::super::NonRefundableTransferToExistingAccountKind,
        ) -> Self {
            Self::NonRefundableTransferToExistingAccount(
                ::buffa::alloc::boxed::Box::new(v),
            )
        }
    }
    impl From<super::super::super::NonRefundableTransferToExistingAccountKind>
    for ::core::option::Option<Kind> {
        fn from(
            v: super::super::super::NonRefundableTransferToExistingAccountKind,
        ) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::GlobalContractDoesNotExist> for Kind {
        fn from(v: super::super::super::GlobalContractDoesNotExist) -> Self {
            Self::GlobalContractDoesNotExist(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::GlobalContractDoesNotExist>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::GlobalContractDoesNotExist) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::GasKeyDoesNotExistKind> for Kind {
        fn from(v: super::super::super::GasKeyDoesNotExistKind) -> Self {
            Self::GasKeyDoesNotExist(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::GasKeyDoesNotExistKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::GasKeyDoesNotExistKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::InsufficientGasKeyBalanceKind> for Kind {
        fn from(v: super::super::super::InsufficientGasKeyBalanceKind) -> Self {
            Self::InsufficientGasKeyBalance(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::InsufficientGasKeyBalanceKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::InsufficientGasKeyBalanceKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::GasKeyBalanceTooHighKind> for Kind {
        fn from(v: super::super::super::GasKeyBalanceTooHighKind) -> Self {
            Self::GasKeyBalanceTooHigh(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::GasKeyBalanceTooHighKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::GasKeyBalanceTooHighKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidNonceIndexKind> for Kind {
        fn from(v: super::super::super::DelegateActionInvalidNonceIndexKind) -> Self {
            Self::DelegateActionInvalidNonceIndex(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DelegateActionInvalidNonceIndexKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::DelegateActionInvalidNonceIndexKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::TotalPromiseInputSizeExceededKind> for Kind {
        fn from(v: super::super::super::TotalPromiseInputSizeExceededKind) -> Self {
            Self::TotalPromiseInputSizeExceeded(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TotalPromiseInputSizeExceededKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::TotalPromiseInputSizeExceededKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::ReceiptStorageProofSizeExceededKind> for Kind {
        fn from(v: super::super::super::ReceiptStorageProofSizeExceededKind) -> Self {
            Self::ReceiptStorageProofSizeExceeded(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::ReceiptStorageProofSizeExceededKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::ReceiptStorageProofSizeExceededKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::MalformedUniversalStateInitKind> for Kind {
        fn from(v: super::super::super::MalformedUniversalStateInitKind) -> Self {
            Self::MalformedUniversalStateInit(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::MalformedUniversalStateInitKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::MalformedUniversalStateInitKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
    impl From<super::super::super::AccountNotInitializedKind> for Kind {
        fn from(v: super::super::super::AccountNotInitializedKind) -> Self {
            Self::AccountNotInitialized(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::AccountNotInitializedKind>
    for ::core::option::Option<Kind> {
        fn from(v: super::super::super::AccountNotInitializedKind) -> Self {
            Self::Some(Kind::from(v))
        }
    }
}
pub mod global_contract_does_not_exist {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Identifier {
        CodeHash(::buffa::alloc::boxed::Box<super::super::super::CryptoHash>),
        AccountId(::buffa::alloc::string::String),
    }
    impl ::buffa::Oneof for Identifier {}
    impl From<super::super::super::CryptoHash> for Identifier {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::CodeHash(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CryptoHash> for ::core::option::Option<Identifier> {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::Some(Identifier::from(v))
        }
    }
}
pub mod action {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Action {
        CreateAccount(
            ::buffa::alloc::boxed::Box<super::super::super::CreateAccountAction>,
        ),
        DeployContract(
            ::buffa::alloc::boxed::Box<super::super::super::DeployContractAction>,
        ),
        FunctionCall(
            ::buffa::alloc::boxed::Box<super::super::super::FunctionCallAction>,
        ),
        Transfer(::buffa::alloc::boxed::Box<super::super::super::TransferAction>),
        Stake(::buffa::alloc::boxed::Box<super::super::super::StakeAction>),
        AddKey(::buffa::alloc::boxed::Box<super::super::super::AddKeyAction>),
        DeleteKey(::buffa::alloc::boxed::Box<super::super::super::DeleteKeyAction>),
        DeleteAccount(
            ::buffa::alloc::boxed::Box<super::super::super::DeleteAccountAction>,
        ),
        Delegate(::buffa::alloc::boxed::Box<super::super::super::SignedDelegateAction>),
        DeployGlobalContract(
            ::buffa::alloc::boxed::Box<super::super::super::DeployGlobalContractAction>,
        ),
        DeployGlobalContractByAccountId(
            ::buffa::alloc::boxed::Box<
                super::super::super::DeployGlobalContractByAccountIdAction,
            >,
        ),
        UseGlobalContract(
            ::buffa::alloc::boxed::Box<super::super::super::UseGlobalContractAction>,
        ),
        UseGlobalContractByAccountId(
            ::buffa::alloc::boxed::Box<
                super::super::super::UseGlobalContractByAccountIdAction,
            >,
        ),
        DeterministicStateInit(
            ::buffa::alloc::boxed::Box<super::super::super::DeterministicStateInit>,
        ),
        TransferToGasKey(
            ::buffa::alloc::boxed::Box<super::super::super::TransferToGasKeyAction>,
        ),
        WithdrawFromGasKey(
            ::buffa::alloc::boxed::Box<super::super::super::WithdrawFromGasKeyAction>,
        ),
        DelegateV2(
            ::buffa::alloc::boxed::Box<super::super::super::SignedDelegateActionV2>,
        ),
        UniversalStateInit(
            ::buffa::alloc::boxed::Box<super::super::super::UniversalStateInitAction>,
        ),
    }
    impl ::buffa::Oneof for Action {}
    impl From<super::super::super::CreateAccountAction> for Action {
        fn from(v: super::super::super::CreateAccountAction) -> Self {
            Self::CreateAccount(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CreateAccountAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::CreateAccountAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeployContractAction> for Action {
        fn from(v: super::super::super::DeployContractAction) -> Self {
            Self::DeployContract(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeployContractAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeployContractAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::FunctionCallAction> for Action {
        fn from(v: super::super::super::FunctionCallAction) -> Self {
            Self::FunctionCall(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::FunctionCallAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::FunctionCallAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::TransferAction> for Action {
        fn from(v: super::super::super::TransferAction) -> Self {
            Self::Transfer(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TransferAction> for ::core::option::Option<Action> {
        fn from(v: super::super::super::TransferAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::StakeAction> for Action {
        fn from(v: super::super::super::StakeAction) -> Self {
            Self::Stake(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::StakeAction> for ::core::option::Option<Action> {
        fn from(v: super::super::super::StakeAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::AddKeyAction> for Action {
        fn from(v: super::super::super::AddKeyAction) -> Self {
            Self::AddKey(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::AddKeyAction> for ::core::option::Option<Action> {
        fn from(v: super::super::super::AddKeyAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeleteKeyAction> for Action {
        fn from(v: super::super::super::DeleteKeyAction) -> Self {
            Self::DeleteKey(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeleteKeyAction> for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeleteKeyAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeleteAccountAction> for Action {
        fn from(v: super::super::super::DeleteAccountAction) -> Self {
            Self::DeleteAccount(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeleteAccountAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeleteAccountAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::SignedDelegateAction> for Action {
        fn from(v: super::super::super::SignedDelegateAction) -> Self {
            Self::Delegate(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::SignedDelegateAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::SignedDelegateAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeployGlobalContractAction> for Action {
        fn from(v: super::super::super::DeployGlobalContractAction) -> Self {
            Self::DeployGlobalContract(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeployGlobalContractAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeployGlobalContractAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeployGlobalContractByAccountIdAction> for Action {
        fn from(v: super::super::super::DeployGlobalContractByAccountIdAction) -> Self {
            Self::DeployGlobalContractByAccountId(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeployGlobalContractByAccountIdAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeployGlobalContractByAccountIdAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::UseGlobalContractAction> for Action {
        fn from(v: super::super::super::UseGlobalContractAction) -> Self {
            Self::UseGlobalContract(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::UseGlobalContractAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::UseGlobalContractAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::UseGlobalContractByAccountIdAction> for Action {
        fn from(v: super::super::super::UseGlobalContractByAccountIdAction) -> Self {
            Self::UseGlobalContractByAccountId(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::UseGlobalContractByAccountIdAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::UseGlobalContractByAccountIdAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::DeterministicStateInit> for Action {
        fn from(v: super::super::super::DeterministicStateInit) -> Self {
            Self::DeterministicStateInit(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::DeterministicStateInit>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::DeterministicStateInit) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::TransferToGasKeyAction> for Action {
        fn from(v: super::super::super::TransferToGasKeyAction) -> Self {
            Self::TransferToGasKey(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::TransferToGasKeyAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::TransferToGasKeyAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::WithdrawFromGasKeyAction> for Action {
        fn from(v: super::super::super::WithdrawFromGasKeyAction) -> Self {
            Self::WithdrawFromGasKey(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::WithdrawFromGasKeyAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::WithdrawFromGasKeyAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::SignedDelegateActionV2> for Action {
        fn from(v: super::super::super::SignedDelegateActionV2) -> Self {
            Self::DelegateV2(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::SignedDelegateActionV2>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::SignedDelegateActionV2) -> Self {
            Self::Some(Action::from(v))
        }
    }
    impl From<super::super::super::UniversalStateInitAction> for Action {
        fn from(v: super::super::super::UniversalStateInitAction) -> Self {
            Self::UniversalStateInit(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::UniversalStateInitAction>
    for ::core::option::Option<Action> {
        fn from(v: super::super::super::UniversalStateInitAction) -> Self {
            Self::Some(Action::from(v))
        }
    }
}
pub mod global_contract_identifier_view {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Identifier {
        CodeHash(::buffa::alloc::boxed::Box<super::super::super::CryptoHash>),
        AccountId(::buffa::alloc::string::String),
    }
    impl ::buffa::Oneof for Identifier {}
    impl From<super::super::super::CryptoHash> for Identifier {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::CodeHash(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CryptoHash> for ::core::option::Option<Identifier> {
        fn from(v: super::super::super::CryptoHash) -> Self {
            Self::Some(Identifier::from(v))
        }
    }
}
pub mod access_key_permission {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Permission {
        FunctionCall(
            ::buffa::alloc::boxed::Box<super::super::super::FunctionCallPermission>,
        ),
        FullAccess(
            ::buffa::alloc::boxed::Box<super::super::super::FullAccessPermission>,
        ),
        GasKeyFunctionCall(
            ::buffa::alloc::boxed::Box<super::super::super::GasKeyFunctionCallPermission>,
        ),
        GasKeyFullAccess(
            ::buffa::alloc::boxed::Box<super::super::super::GasKeyFullAccessPermission>,
        ),
    }
    impl ::buffa::Oneof for Permission {}
    impl From<super::super::super::FunctionCallPermission> for Permission {
        fn from(v: super::super::super::FunctionCallPermission) -> Self {
            Self::FunctionCall(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::FunctionCallPermission>
    for ::core::option::Option<Permission> {
        fn from(v: super::super::super::FunctionCallPermission) -> Self {
            Self::Some(Permission::from(v))
        }
    }
    impl From<super::super::super::FullAccessPermission> for Permission {
        fn from(v: super::super::super::FullAccessPermission) -> Self {
            Self::FullAccess(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::FullAccessPermission>
    for ::core::option::Option<Permission> {
        fn from(v: super::super::super::FullAccessPermission) -> Self {
            Self::Some(Permission::from(v))
        }
    }
    impl From<super::super::super::GasKeyFunctionCallPermission> for Permission {
        fn from(v: super::super::super::GasKeyFunctionCallPermission) -> Self {
            Self::GasKeyFunctionCall(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::GasKeyFunctionCallPermission>
    for ::core::option::Option<Permission> {
        fn from(v: super::super::super::GasKeyFunctionCallPermission) -> Self {
            Self::Some(Permission::from(v))
        }
    }
    impl From<super::super::super::GasKeyFullAccessPermission> for Permission {
        fn from(v: super::super::super::GasKeyFullAccessPermission) -> Self {
            Self::GasKeyFullAccess(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::GasKeyFullAccessPermission>
    for ::core::option::Option<Permission> {
        fn from(v: super::super::super::GasKeyFullAccessPermission) -> Self {
            Self::Some(Permission::from(v))
        }
    }
}
